from os.path import join as pjoin
import sys

DATA_DIR = "../data/"
RAW_DATA_DIR = pjoin(DATA_DIR, "raw")
RAW_LARGE_DATA_DIR = pjoin(RAW_DATA_DIR, 'large')
INTERIM_DATA_DIR = pjoin(DATA_DIR, "interim")
PAPER_CLASSIFICATION_TASK = pjoin(INTERIM_DATA_DIR, 'paper_classification_task')
INTERIM_LARGE_DATA_DIR = pjoin(INTERIM_DATA_DIR, 'large')
AFF_CODING_RESULTS = pjoin(INTERIM_DATA_DIR, 'aff_result')
GENDER_AND_RACE_CODING_RESULTS = pjoin(INTERIM_DATA_DIR, 'gender_race_result')
PROCESSED_DATA_DIR = pjoin(DATA_DIR, "processed")

###############################################################################
# Raw Data
###############################################################################

# SSCI journals 
SSCI = pjoin(RAW_DATA_DIR, 'ssci.csv')

ROR_RAW_DATA = pjoin(RAW_LARGE_DATA_DIR, 'ror.json')

###############################################################################
# Interim outputs
###############################################################################

ICA_PAPER_DF = pjoin(INTERIM_DATA_DIR, 'ica_paper_df.csv')

ICA_PAPER_DATA = pjoin(INTERIM_DATA_DIR, 'ica_paper_data.csv')
ICA_AUTHOR_DATA = pjoin(INTERIM_DATA_DIR, 'ica_author_data.csv')
ICA_ERROR_URLS = pjoin(INTERIM_DATA_DIR, 'ica_error_urls.txt')

ICA_AUTHOR_DF = pjoin(INTERIM_DATA_DIR, 'ica_author_df.csv')
NO_AUTHOR_URLS = pjoin(INTERIM_DATA_DIR, 'no_author_urls.txt')

AUTHOR_WITH_GENDER = pjoin(INTERIM_DATA_DIR, 'author_with_gender.csv')

AUTHOR_WITH_PRED_RAW = pjoin(INTERIM_DATA_DIR, 'author_with_pred_raw.csv')

PAPER_CLASSIFICATION_HONGTAO = pjoin(
    PAPER_CLASSIFICATION_TASK, 
    'paper_classification_hongtao.csv')
PAPER_CLASSIFICATION_JEFF = pjoin(PAPER_CLASSIFICATION_TASK, 
    'paper_classification_jeff.csv')
PAPER_CLASSIFICATION_KRISTEN = pjoin(PAPER_CLASSIFICATION_TASK, 
    'paper_classification_kristen.csv')

HONGTAO_AFF_RESULT = pjoin(AFF_CODING_RESULTS, 'hongtao.csv')
KRISTEN_AFF_RESULT = pjoin(AFF_CODING_RESULTS, 'kristen.csv')

# GR means gender and race
HALEY_GR_RESULT = pjoin(GENDER_AND_RACE_CODING_RESULTS, 'haley.csv')
JAEMIN_GR_RESULT = pjoin(GENDER_AND_RACE_CODING_RESULTS, 'JAEMIN.csv')
JONGMIN_GR_RESULT = pjoin(GENDER_AND_RACE_CODING_RESULTS, 'jongmin.csv')
MATTHEW_GR_RESULT = pjoin(GENDER_AND_RACE_CODING_RESULTS, 'matthew.csv')
JEFF_GR_RESULT = pjoin(GENDER_AND_RACE_CODING_RESULTS, 'jeff.csv')
MICHELLE_GR_RESULT = pjoin(GENDER_AND_RACE_CODING_RESULTS, 'michelle.csv')

# This is the gender results for those whose first names are initials only
INITIAL_DF = pjoin(GENDER_AND_RACE_CODING_RESULTS, 'initial_df.csv')

## Google Scholar
GSCHOLAR_DATA_MANUAL_CHECKED = pjoin(INTERIM_DATA_DIR, 'gscholar_data_manual_checked.csv')

###############################################################################
# Processed outputs
###############################################################################

AUTHOR_WITH_PRED = pjoin(PROCESSED_DATA_DIR, 'author_with_pred.csv')
ICA_PAPER_DF_WITH_TYPE = pjoin(PROCESSED_DATA_DIR, 'ica_paper_df_with_type.csv')
RESEARCH_PAPER_DF = pjoin(PROCESSED_DATA_DIR, 'research_paper_df.csv')

AUTHOR_WITH_PRED_WITH_TYPE = pjoin(PROCESSED_DATA_DIR, 'author_with_pred_with_type.csv')
RESEARCH_AUTHOR_WITH_PRED = pjoin(PROCESSED_DATA_DIR, 'research_author_with_pred.csv')

AUTHORS_TO_STUDY = pjoin(PROCESSED_DATA_DIR, 'authors_to_study.csv')
DOIS_TO_STUDY = pjoin(PROCESSED_DATA_DIR, 'dois_to_study.txt')
PAPERS_TO_STUDY = pjoin(PROCESSED_DATA_DIR, 'papers_to_study.csv')

AUTHORID_WITH_VARS = pjoin(PROCESSED_DATA_DIR, 'authorid_with_variables.csv')

AUTHORS_TO_STUDY_EXPANDED = pjoin(PROCESSED_DATA_DIR, 'authors_to_study_expanded.csv')
PAPERS_TO_STUDY_EXPANDED = pjoin(PROCESSED_DATA_DIR, 'papers_to_study_expanded.csv')

GSCHOLAR_DATA = pjoin(PROCESSED_DATA_DIR, 'gscholar_data.csv')

GSCHOLAR_DATA_COMBINED = pjoin(PROCESSED_DATA_DIR, 'gscholar_data_combined.csv')

###############################################################################
# Workflows
###############################################################################

rule all:
    input:
        # ICA_PAPER_DF,
        # ICA_PAPER_DATA,
        # ICA_AUTHOR_DATA,
        # ICA_ERROR_URLS,
        # AUTHOR_WITH_GENDER,
        # AUTHOR_WITH_PRED_RAW,
        # AUTHOR_WITH_PRED,
        # ICA_PAPER_DF_WITH_TYPE, 
        # AUTHOR_WITH_PRED_WITH_TYPE,
        # RESEARCH_PAPER_DF,
        # RESEARCH_AUTHOR_WITH_PRED,
        # AUTHORS_TO_STUDY,
        # DOIS_TO_STUDY,
        # PAPERS_TO_STUDY,
        # AUTHORID_WITH_VARS,
        AUTHORS_TO_STUDY_EXPANDED,
        PAPERS_TO_STUDY_EXPANDED,
        # GSCHOLAR_DATA,
        # GSCHOLAR_DATA_COMBINED,

# # scrape ica paper dois
# rule scrape_ica_paper_dois:
#     output: ICA_PAPER_DF
#     shell: "python scripts/scrape_ica_paper_dois.py {output}"

# # scrape ica author and paper data
# rule scrape_ica_author_data:
#     input: ICA_PAPER_DF
#     output: ICA_PAPER_DATA, ICA_AUTHOR_DATA, ICA_ERROR_URLS
#     shell: "python scripts/scrape_ica_author_data.py {input} {output}"

# # get author gender raw predictions
# rule get_author_with_gender:
#     input: ICA_AUTHOR_DATA, 
#     output: AUTHOR_WITH_GENDER
#     shell: "python scripts/get_author_with_gender.py {input} {output}"

# # get race and affiliations. Raw because I'll change column order later
# rule get_author_with_pred_raw:
#     input: 
#         AUTHOR_WITH_GENDER, 
#         ROR_RAW_DATA
#     output: AUTHOR_WITH_PRED_RAW
#     shell: "python scripts/get_author_with_pred_raw.py {input} {output}"

# # rearrange colomn order
# rule get_author_with_pred:
#     input: AUTHOR_WITH_PRED_RAW
#     output: AUTHOR_WITH_PRED
#     shell: "python scripts/get_author_with_pred.py {input} {output}"

# # add 'type' to paper df and author data
# rule get_paper_and_author_with_type:
#     input: 
#         PAPER_CLASSIFICATION_HONGTAO,
#         PAPER_CLASSIFICATION_JEFF,
#         PAPER_CLASSIFICATION_KRISTEN,
#         ICA_PAPER_DF,
#         AUTHOR_WITH_PRED,

#     output: ICA_PAPER_DF_WITH_TYPE, 
#             AUTHOR_WITH_PRED_WITH_TYPE,
#             RESEARCH_PAPER_DF,
#             RESEARCH_AUTHOR_WITH_PRED,
#             AUTHORS_TO_STUDY,
#             DOIS_TO_STUDY,
#             PAPERS_TO_STUDY
#     shell: "python scripts/get_paper_and_author_with_type.py {input} {output}"

# rule get_authorid_with_vars:
#     input:
#         ROR_RAW_DATA,
#         HONGTAO_AFF_RESULT,
#         KRISTEN_AFF_RESULT,
#         HALEY_GR_RESULT,
#         JAEMIN_GR_RESULT,
#         JONGMIN_GR_RESULT,
#         MATTHEW_GR_RESULT,
#         JEFF_GR_RESULT,
#         MICHELLE_GR_RESULT,
#         INITIAL_DF,

#     output:
#         AUTHORID_WITH_VARS
#     shell: 'python scripts/get_authorid_with_vars.py {input} {output}'

rule get_authors_and_papers_expanded:
    input:
        AUTHORID_WITH_VARS,
        AUTHORS_TO_STUDY,
        PAPERS_TO_STUDY,
        GSCHOLAR_DATA_COMBINED,

    output:
        AUTHORS_TO_STUDY_EXPANDED,
        PAPERS_TO_STUDY_EXPANDED,
    shell: 'python scripts/get_authors_and_papers_expanded.py {input} {output}'

# rule get_gscholar_data:
#     input: AUTHORS_TO_STUDY
#     output: GSCHOLAR_DATA
#     shell: 'python scripts/get_gscholar_data.py {input} {output}'

# rule get_gscholar_data_combined:
#     input: GSCHOLAR_DATA, GSCHOLAR_DATA_MANUAL_CHECKED
#     output: GSCHOLAR_DATA_COMBINED
#     shell: 'python scripts/get_gscholar_data_combined.py {input} {output}'
